# Site settings
title: Nicholas Auger
header-img: img/home-bg.jpg
email: nauger@unca.edu
description: "My name is Nicholas Auger I'm a Web Developer from North Carolina and this is my blog. "
baseurl: ""
url: "http://www.qkombur.com"
twitter_username: qkombur
github_username:  qkombur

# Build settings

markdown: kramdown
permalink: pretty
